package com.henheang.securityapi.domain;

public enum AuditEventType {
    SIGNUP,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    LOGOUT,
    TOKEN_REVOKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    MFA_SETUP_INITIATED,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_DISABLE_FAILED,
    MFA_CHALLENGE_FAILED,
    MFA_BACKUP_CODE_USED,
    MFA_BACKUP_CODES_REGENERATED,
    EMAIL_VERIFICATION_REQUESTED,
    EMAIL_VERIFIED,
    ACCOUNT_UNLOCK_REQUESTED,
    ACCOUNT_UNLOCKED
}
